application: persistent-cal-golang
version: 0-1
runtime: go
api_version: go1.4beta

error_handlers:
  - file: templates/500.html

handlers:
# precedence should be noted for any wildcards
- url: /favicon\.ico
  static_files: images/favicon.ico
  upload: images/favicon\.ico

- url: /stylesheets
  static_dir: stylesheets

- url: /javascript
  static_dir: javascript

- url: /_ah/remote_api
  script: _go_app
  login: admin

- url: /.*
  script: _go_app
